
#####################
#   U  U  H H   CCC
#   U  U  HHH  C
#    UU   H H   CCC
#####################

rulesets:
    - Default: net.nightpool.bukkit.uhcplugin.game.DefaultRules
    - Spectators: net.nightpool.bukkit.uhcplugin.game.SpectatorRules
    - Scatter: net.nightpool.bukkit.uhcplugin.game.ScatterRules
    - Teams: net.nightpool.bukkit.uhcplugin.game.TeamRules
    - EternalDaytime: net.nightpool.bukkit.uhcplugin.game.EternalDaytime